language: cpp
dist: xenial

script:
    ############################################################################
    # Build main and tests
    ############################################################################
     - sh download_torch.sh
     - mkdir -p build
     - cd build
     - cmake ..
     - make
     - make test